trigger:
- develop
- master

pool:
  vmImage: 'windows-2019'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        useGlobalJson: true
    - task: PowerShell@2
      displayName: "Restore, Compile, Test, and Package"
      inputs:
        filePath: 'build.ps1'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: './build-artifacts/coverage-reports/Cobertura.xml'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/*.trx'
        mergeTestResults: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: './build-artifacts/packages'
        ArtifactName: 'packages'
        publishLocation: 'Container' 