// Copyright (c) GraphZen LLC. All rights reserved.
// Licensed under the GraphZen Community License. See the LICENSE file in the project root for license information.

using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using GraphZen.Infrastructure;

[assembly: InternalsVisibleTo("GraphZen")]
[assembly: InternalsVisibleTo("GraphZen.Client")]
[assembly: InternalsVisibleTo("GraphZen.Client.Tests")]
[assembly: InternalsVisibleTo("GraphZen.Client.IntegrationTests")]
[assembly: InternalsVisibleTo("GraphZen.Client.FunctionalTests")]
[assembly: InternalsVisibleTo("GraphZen.AspNetCore")]
[assembly: InternalsVisibleTo("GraphZen.AspNetCore.Server")]
[assembly: InternalsVisibleTo("GraphZen.AspNetCore.Server.Tests")]
[assembly: InternalsVisibleTo("GraphZen.AspNetCore.Server.IntegrationTests")]
[assembly: InternalsVisibleTo("GraphZen.AspNetCore.Server.FunctionalTests")]
[assembly: InternalsVisibleTo("GraphZen.AspNetCore.Playground")]
[assembly: InternalsVisibleTo("GraphZen.AspNetCore.Playground.Tests")]
[assembly: InternalsVisibleTo("GraphZen.AspNetCore.Playground.IntegrationTests")]
[assembly: InternalsVisibleTo("GraphZen.AspNetCore.Playground.FunctionalTests")]
[assembly: InternalsVisibleTo("GraphZen.Tests")]
[assembly: InternalsVisibleTo("GraphZen.Infrastructure.Testing.Tests")]
[assembly: InternalsVisibleTo("GraphZen.Infrastructure.Testing")]
[assembly: InternalsVisibleTo("GraphZen.Infrastructure")]
[assembly: InternalsVisibleTo("GraphZen.AspNetCore")]
[assembly: InternalsVisibleTo("GraphZen.Abstractions")]
[assembly: InternalsVisibleTo("GraphZen.Abstractions.Tests")]
[assembly: InternalsVisibleTo("GraphZen.DevCli")]
[assembly: InternalsVisibleTo("GraphZen.DevCli.Tests")]
[assembly: InternalsVisibleTo("GraphZen.LanguageModel")]
[assembly: InternalsVisibleTo("GraphZen.LanguageModel.Tests")]
[assembly: InternalsVisibleTo("GraphZen.LanguageModel.FunctionalTests")]
[assembly: InternalsVisibleTo("GraphZen.LanguageModel.IntegrationTests")]
[assembly: InternalsVisibleTo("GraphZen.QueryEngine")]
[assembly: InternalsVisibleTo("GraphZen.QueryEngine.Tests")]
[assembly: InternalsVisibleTo("GraphZen.QueryEngine.FunctionalTests")]
[assembly: InternalsVisibleTo("GraphZen.TypeSystem")]
[assembly: InternalsVisibleTo("GraphZen.TypeSystem.Tests")]
[assembly: InternalsVisibleTo("GraphZen.TypeSystem.IntegrationTests")]
[assembly: InternalsVisibleTo("GraphZen.TypeSystem.FunctionalTests")]
[assembly: InternalsVisibleTo("LINQPadQuery")]